### ISSUE TITLE
Race condition for .change() event

### ISSUE THREAD

**Issue by jgoyvaerts** [tristanjahier/chosen-order#2]
When calling .getSelectedOrder() in a .change() event handler on the chosen element, I got the results before the actual change event happened (so when an item was selected, it would return all the items except the newly selected one), indicating a race event. When calling the function anywhere else, it worked fine.

I tried making a jsfiddle to demonstrate the problem but jsfiddle is being weird when I add chosen-order into it.

I solved my problem by moving the .getSelectedOrder() call to the end of the event stack (with setTimeout(func, 0)), but that seems far from ideal.

**Comment by tristanjahier** [comment]
Hey @jgoyvaerts. Chosen Order has changed a bit since you reported this issue.
Do you still experience this issue? Did you solved that?
Chosen Order do work on JsFiddle now (links on README.md).

Does this JsFiddle reflect well your problem? http://jsfiddle.net/9sfq9oqt/1

**Comment by jgoyvaerts** [comment]
Yes thats a good reflection of the problem. As you can see here, without the timeout:

http://jsfiddle.net/9sfq9oqt/2/

Try removing 2 elements from the list. It only updates after removing the second element, because there's a race condition between the actual change happening and the order being shown.

If that's intended or necessary for this library to work, that's fine, setTimeout is an "okay" workaround, but maybe it can be added to the readme then?

**Comment by tristanjahier** [comment]
Ok, I experienced this exact problem without `setTimeout(func, 0)`.
But, what is weird is that if you **add** an element, the update comes **before** the call of `getSelectionOrder()` and there is no issue.

Concerning this problem, I'm afraid it is not up to me. Indeed, Chosen Order does not use custom events, apart from `chosen:updated` in `setSelectionOrder()`.
IMO, I think the problem could be handle properly only by Chosen itself.

Plus, I'm not an expert in asynchronous Javascript and I have no idea how a race condition could be solved.

You're right, the `setTimeout` workaround can be added to the README.

**Comment by juliandkatz** [comment]
I am having the same issue as @jgoyvaerts 

Are you sure this is a problem with chosen itself?  Running a .val() on the chosen after the .change event returns the correct (though un-ordered) list, while getSelectionOrder fails due to the race condition as indicated by @jgoyvaerts.  

Thanks for putting in the time on this, it's quite a useful tool for me!

**Comment by juliandkatz** [comment]
Here is the work-around that I used, which I think superior to the setTimeout().

Call getSelectedOrder on the .change event, retrieving the incorrect, ordered list.  Use jquery to grab the value of the correct, unordered list (  $("#myChosen").val()  ).

Next, check the incorrect, ordered list (getSelectedOrder) against the correct, unordered one (val).  This can be done with a for loop, but I used underscore's _.filter function, combined with the underscore _.contains function.

```
    var filteredValues = _.filter(incorrectOrdered, function(value) {
        return _.contains(correctUnordered, value);
    });
```

Hope that's useful!

**Comment by tristanjahier** [comment]
Hi @juliankatz1991 and thanks for you support.
I don't say that Chosen itself creates the problem, but that it may be handled more properly from its POV. This problem is not a bug in Chosen nor Chosen Order, it just "happens" in between.

The callback passed to the `change()` function seems to be called by Chosen before the DOM is actually updated and so when Chosen Order computes the ordered selection by browsing the DOM, the option has not been removed yet and is still part of the selection.
At least that's what I think...

Your workaround is interesting. The `val()` function of jQuery returns the good selection because it applies on the original `<select>` element which has already been updated.
