### ISSUE TITLE
<optgroup> support

### ISSUE THREAD

**Issue by guypaskar** [tristanjahier/chosen-order#3]
Is chosen-order  supports a select with optgroup?

It does not seem to work.

**Comment by jtoliver** [comment]
It might be a little late, but I created a pr https://github.com/tristanjahier/chosen-order/pull/5
I needed the same functionality.

**Comment by tristanjahier** [comment]
Hello @guypaskar and @jtoliver! :)

I'm back with Chosen Order and I finally dealt with this issue. I have never used <optgroup> before and that's why I've never been aware of the problem. Today, I tried and figured out that, indeed, it crashes.

I figured out that Chosen uses really weird relative indexes for the <option>s when there are <optgroup>s... :s
But anyway, in a couple of hours I've achieved to solve the problem in an elegant manner (at least I hope). :D

Hold on a bit more, I'll push my work (very) soon.

**Comment by tristanjahier** [comment]
@guypaskar Check out this branch: https://github.com/tristanjahier/chosen-order/tree/add-optgroup-support and let me know if your problem is solved.

**Comment by guypaskar** [comment]
Will test it later this week and let you know.

Thanks!

**Comment by tristanjahier** [comment]
@guypaskar OK. You can directly check out the `master` branch, I've merged them.
