### ISSUE TITLE
Order is wrong when you remove the item

### ISSUE THREAD

**Issue by aamirafridi** [tristanjahier/chosen-order#7]
Take this example http://jsfiddle.net/RA8ej/92/

Remove item and check the alert.

The temp solution is http://jsfiddle.net/RA8ej/93/ but order plugin should listen to change event properly.

Also if an item is not selected and is in order list, it shows an error `Uncaught TypeError: Failed to execute 'insertBefore' on 'Node': parameter 1 is not of type 'Node'.` check console in this example http://jsfiddle.net/RA8ej/94/. Ideally it should just ignore the item which is not selected.

**Comment by tristanjahier** [comment]
Hello @aamirafridi,

This issue is well-known and has already been reported and addressed here: https://github.com/tristanjahier/chosen-order/issues/2 and https://github.com/tristanjahier/chosen-order/issues/6.

As I said to the others, I have been unable to find out a good solution for the moment. When you remove an item, my script executes **before** the DOM is actually updated and I don't know why or how to tacle properly this issue. I find even more bizarre that this is not the case when and item is added...

However, the `setTimeout(func, 0)` works very well and should not be a problem to use.
You can find another workaround in the links I have just given to you.
I am currently developing `version 2.0`, and you can find more information about this issue in the README.md: https://github.com/tristanjahier/chosen-order/blob/2.x/dev/README.md#binding-selection-retrieval-on-chosen-change-event.

---

About your second problem, if you only want to ensure that the selection matches exactly what you want, just pass a second parameter to `setSelectionOrder`:

```
$chosen.setSelectionOrder(order, true);
```

It forces the selection of the values **before** trying to order them and consequently solves your problem.

That said, I agree that it should just ignore the items which are not selected in the default case, and I will make a fix for this.

**Comment by tristanjahier** [comment]
Checkout branch `1.x/dev` https://github.com/tristanjahier/chosen-order/tree/1.x/dev and let me know if it solves your second problem.

Options which are in the ordered selection but not in the Chosen select element will now be ignored, but a warning will be output in the console.

**Comment by aamirafridi** [comment]
I will wait for version2.0 :+1: 
Thanks for the reply.
